#!/bin/bash

: '

Update config paths with configs to bundle.

'

CONFIG_PATHS=(
              "/home/$USER/.tmux.conf"
              "/home/$USER/.config/alacritty"
              "/home/$USER/.config/i3"
              "/home/$USER/.config/polybar"
              "/home/$USER/.config/nvim"
              "/home/$USER/.local/share/fonts"
              "/home/$USER/.bashrc"
              "/home/$USER/.bash_profile"
              "/home/$USER/.profile"
              
              )

if [ "$1" == "bundle" ];
then
    rm -rf bundled_configs && mkdir bundled_configs
    echo "Bundeling my configurations files."

    for dir in ${CONFIG_PATHS[@]}; do
        cp -r $dir /home/$USER/dotfiles/bundled_configs
        echo Bundling: $dir
    done

else
    echo "Bad argument."
fi


