#!/bin/bash

: '

Update config paths with configs to bundle.

'

CONFIG_PATHS=(
              "/home/$USER/.tmux.conf"
              "/home/$USER/.config/alacritty"
              "/home/$USER/.config/i3"
              "/home/$USER/.config/polybar"
              "/home/$USER/.config/nvim"
              "/home/$USER/.config/fish"
              "/home/$USER/.bashrc"
              "/home/$USER/.bash_profile"
              "/home/$USER/.profile"
              
              )

if [ "$1" == "bundle" ];
then
    rm -rf configs && mkdir configs
    echo "Bundeling configurations files."

    for dir in ${CONFIG_PATHS[@]}; do
        cp -r $dir /home/$USER/dotfiles/configs
        echo Bundling: $dir
    done
fi
if [ "$1" == "install" ];
then
    # These should all go into .config
    # Choosing to copy instead of moving to not override the files 
    # in the current directory if needed for manual transactions.
    for file in "./configs"/* ; do
        cp -r $file "/home/$USER/.config"
    done

    # These should go into /home/$USER
    for file in "./configs"/.[^.]* ; do
        cp -r $file "/home/$USER"
    done

fi


