#!/bin/bash

: '

Update config paths with configs to bundle.

'

CONFIG_PATHS=(
              "/home/$USER/.tmux.conf"
              "/home/$USER/.config/alacritty"
              "/home/$USER/.config/i3"
              "/home/$USER/.config/polybar"
              "/home/$USER/.config/nvim"
              "/home/$USER/.config/fish"
              "/home/$USER/.bashrc"
              "/home/$USER/.bash_profile"
              "/home/$USER/.profile"
              
              )

if [ "$1" == "bundle" ];
then
    rm -rf configs && mkdir configs
    echo "Bundeling configurations files."

    for dir in ${CONFIG_PATHS[@]}; do
        cp -r $dir /home/$USER/dotfiles/configs
        echo Bundling: $dir
    done

fi
if [ "$1" == "install" ];
then
    for dir in ${CONFIG_PATHS[@]}; do
        echo "todo install $dir"
    done
fi


